# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b4d6c1659f9daa9f25c8013ba6634c391bde85f26fa4d7e6ee6e411098241a9fbbdfeab47b0defbe93776f0d4d69c5fe53b3a480335d923b46e2d550537238a
  PAYJP_ACCESS_KEY: sk_test_1be3aacbcbcc41ba0aaf616c
  payjp_access_key: <%= ENV["PAYJP_ACCESS_KEY"] %>
  PAYJP_PUBLIC_KEY: pk_test_8444f02a03411a8548760003
  payjp_public_key: <%= ENV["PAYJP_PUBLIC_KEY"] %>
  
test:
  secret_key_base: 70ec499e6a5757a62c1f29ce1657f497d4ee5c2897b4d9aa31d7eb1d5db1c2aa96babdaaa9f0ad1d3cfc7ac4ab95c02e374f0f4c492778a4b14611484677fa53

payjp:
 PAYJP_ACCESS_KEY: sk_test_1be3aacbcbcc41ba0aaf616c
 payjp_access_key: <%= ENV["PAYJP_ACCESS_KEY"] %>
 PAYJP_PUBLIC_KEY: pk_test_8444f02a03411a8548760003
 payjp_public_key: <%= ENV["PAYJP_PUBLIC_KEY"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

  payjp_access_key: <%= ENV["PAYJP_ACCESS_KEY"] %>
  payjp_public_key: <%= ENV["PAYJP_PUBLIC_KEY"] %>


